# Pre-commit configuration for minFM
repos:
# Ruff linter and formatter
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
  # Run the linter
  - id: ruff
    args: [ --fix ]
  # Run the formatter
  - id: ruff-format

# Additional useful pre-commit hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  # Check for files that would conflict in case-insensitive filesystems
  - id: check-case-conflict
  # Check for files that contain merge conflict strings
  - id: check-merge-conflict
  # Check YAML files for parseable syntax
  - id: check-yaml
  # Check TOML files for parseable syntax
  - id: check-toml
  # Ensure that a file is either empty or ends with one newline
  - id: end-of-file-fixer
    types: [ python ]
  # Remove trailing whitespace (including spaces/tabs on blank lines)
  - id: trailing-whitespace
    types: [ python ]

default_language_version:
  python: python3
